ruby-grape/grape-swagger-rails

- .travis.yml
Hi there,
I confirmed ruby 1.9.3 does not work with grape-swagger-rails on this part. 
```erb
<html data-swagger-options="<%= GrapeSwaggerRails.options.to_h.to_json %>">
```
I know 1.9.3 is not maintained anymore but I think it's still kind to clarify the ruby version if possible . (Yes, I'm still using 1.9.3 in some projects...)
I confirmed 2.0.0 works with rails 3.2 so I added '2.0.0' as the compatible version. (.travis.yml uses 2.1.2, though.)
Let me know if I'm missing something.
Thank you!
> [ci-skip] Clarify compatible ruby version

- CHANGELOG.md
- README.md
- app/views/grape_swagger_rails/application/index.html.erb
- lib/grape-swagger-rails.rb
- spec/features/swagger_spec.rb
This Pull Request will support to use docExpansion option.
```ruby
GrapeSwaggerRails.options.doc_expansion = 'list'
```
> Add support for docExpansion option

- .travis.yml
- CHANGELOG.md
- app/views/grape_swagger_rails/application/index.html.erb
grape-swagger-rails currently breaks on Ruby < 2.0 cause it relies on `OpenStruct#to_h`, which is new. `OpenStruct#marshal_dump` is equivalent and is backwards compatible
Also consider adding v1.9.3 to the Travis matrix?
> use Ostruct#marshal_dump instead of #to_h to support Ruby 1.9.3

- CHANGELOG.md
- app/views/grape_swagger_rails/application/index.html.erb
- spec/features/swagger_spec.rb
My application use auth by headers content.
When Swagger UI fetch source from swagger documentation path it return 401 because headers sets after call _swaggerUI.load()_ and request for swagger documentation dosen't include auth headers.
In my version headers sets in initialize swaggerUI object and when _swaggerUI.load() _call request for fetch documantation include header
> Headers added before  swaggerUi.load() call.

- CHANGELOG.md
- README.md
- app/views/grape_swagger_rails/application/index.html.erb
- spec/features/swagger_spec.rb
When you are running Swagger-UI on a server which is not open to external access, the default validation behavior causes an error message to be displayed. This change allows you to set a validator_url option to nil, which suppresses this error message. You could also point to a validator service under your own control.
> Support Swagger-UI validatorUrl option.

- CHANGELOG.md
- app/views/grape_swagger_rails/application/index.html.erb
Hello! I don't believe this is a ready-to-merge PR, but I thought that this would be the best way to start a discussion of it.
In the discussion of PR #25, @supagroova mentioned a change he had made to the index template which fixed some issues with using authorization headers. I found that a variant on this change was necessary to get my own authorization headers working properly, because otherwise the headers just didn't get sent with requests at all.
The change shown in this PR is similar to what I read on PR #25, except that I kept in the code which gets the api_auth, api_key_name and api_key_type from the grape-swagger-rails configuration. It seems to fix the issue for me, without causing any regressions. 
However, I'm unsure how best to write a test that demonstrates that this fixes …
> Fix authorization headers feature

- CHANGELOG.md
- grape-swagger-rails.gemspec
While this gem was constructed with `grape` and `grape-swagger` in mind, they are technically not necessary for non-test purposes.  This will address [this issue](https://github.com/ruby-grape/grape-swagger-rails/issues/60).
> Remove grape and grape-swagger from dependencies

- .ruby-gemset
- spec/features/swagger_spec.rb
Add a spec checking that the supplied options are correctly parsed from the html element's data attribute.
> check that the options are correctly parsed from html

- README.md
Update README to show how to prefill API KEY in Swagger UI with DoorKeeper.
> Integration with DoorKeeper

- CHANGELOG.md
- README.md
- UPGRADING.md
- app/controllers/grape_swagger_rails/application_controller.rb
- lib/grape-swagger-rails.rb
- spec/features/swagger_spec.rb
- replaced `before_filter` usages with `before_action`
- added a deprecation warning to `GrapeSwaggerRails.options.before_filter` option
> Rails 5 support

- CHANGELOG.md
- lib/grape-swagger-rails.rb
- spec/features/swagger_spec.rb
This should better match semantic versioning after Rails 5 related changes were merged (#70). 
- Since we deprecated `before_filter` option and it is a public API - we must increment a minor version (http://semver.org/#spec-item-7)
- Also changed a deprecation warning to refer version `1.0.0` when `before_filter` option and its deprecation warning should be removed  (http://semver.org/#spec-item-8)
> update version references to match semantic versioning properly

- README.md
This PR removes the badge for a service which has disappeared.
> README: Remove defunct gemnasium badge

- .travis.yml
This CI change is about installing Bundler "before 2.0", so that `BUNDLED_WITH` markers in Gemfile.lock do not stop the build.
> Travis: Try to fix build - use Bundler is 1.x, specify exact Firefox version to use

- CHANGELOG.md
- README.md
- app/views/grape_swagger_rails/application/index.html.erb
- spec/features/swagger_spec.rb
Hey guys, first things first: thanks for this great gem! 
It would be quite useful to have a new `token` authentication type,
which follows the Rails convention. So the `Authorization` header
looks like this:
```
Authorization: Token token="WCZZYjnOQFUYfJIN2ShH1iD24UHo58A6TI"
```
This PR allows the usage of this authentication.
> Added the token api_auth type

- .github/workflows/danger.yml
- .github/workflows/test.yml
- CHANGELOG.md
- Gemfile
- README.md
- grape-swagger-rails.gemspec
- spec/dummy/config/initializers/inflections.rb
This adds a test matrix for multiple versions of Ruby and `grape-swagger`.
I've tried to leave as much the same as I could, but some changes were necessary and I've also made a few guesses here:
- Support Ruby 2.7+
- Support `grape-swagger` >= 1.6.0
- The old matrix had very old versions of the package, the most recent being from June 2019. I can add some more recent versions to the matrix if requested and can see what happens, but am not sure how many different versions we want to support.
- Support `railties` >= 6
- Added inflections initializer for `Failure/Error: mount API => '/'`
- Sorted Gemfile
- Updated `mime-types` for error on Ruby 3 ` SyntaxError: /home/runner/work/grape-swagger-rails/grape-swagger-rails/vendor/bundle/ruby/3.0.0/gems/mime-types-2.99.3/lib/mime/types/logger.rb:26 …
> Add test matrix for multiple Ruby versions & update dependencies

- CHANGELOG.md
- lib/grape-swagger-rails.rb
Following an upgrade of the `json` gem we are seeing the following error:
```
.../.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/grape-swagger-rails-0.4.0/lib/grape-swagger-rails.rb:4:in `<module:GrapeSwaggerRails>': uninitialized constant GrapeSwaggerRails::OpenStruct (NameError)
class Options < OpenStruct
```
It turns out that `grape-swagger-rails` depends on `ostruct` being required elsewhere in the app. This was being done for us by `json` and with version 2.7.2 ostruct has become optional. See https://github.com/flori/json/pull/565
One solution is to add `require 'ostruct'` immediately prior to where it is used. This is done in this PR.
Another solution would be to not use OpenStruct as it is now discouraged - see https://docs.ruby-lang.org/en/3.0/OpenStruct.html#class-OpenStruct-labe …
> Ensure that ostruct is loaded

- CHANGELOG.md
- grape-swagger-rails.gemspec
> Fix rubygems source code location metadata.

- .github/workflows/head.yml
- .github/workflows/test.yml
- CHANGELOG.md
Fixes this warning during spec runs:
```
WARN Selenium [:selenium_manager] The geckodriver version (0.32.2) detected in PATH at /opt/hostedtoolcache/geckodriver/0.32.2/x64/geckodriver might not be compatible with the detected firefox version (130.0); currently, geckodriver 0.35.0 is recommended for firefox 130.*, so it is advised to delete the driver in PATH and retry 
```
- #125
Updates CI matrix so it will be easier to add Ruby 3.3
Bumps grape-swagger to 2.1.1 so it runs with the latest grape release again
> Bump firefox and geckodriver

- .github/workflows/test.yml
- CHANGELOG.md
- grape-swagger-rails.gemspec
Fixes #121 
The `ostruct` gem was historically included in the default gems included with Ruby. Starting with Ruby 3.3.5 though, requiring `ostruct` without explicitly adding it as dependency generates the following warning:
warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
As of Ruby 3.5, the `ostruct` gem will then no longer be shipped with Ruby so we need to explicitly add it to the dependencies.
- #124
Fixes CI
- #125
Updates CI matrix so it will be easier to add Ruby 3.3
Bumps grape-swagger to 2.1.1 so it runs with the latest grape release again
> Ruby 3.5 compatibility

- CHANGELOG.md
- Gemfile
- README.md
- lib/grape-swagger-rails/engine.rb
- lib/grape-swagger-rails/version.rb
- spec/dummy/app/assets/config/manifest.js
Automatically register assets with Sprockets.
This removes the need for users of the gem to add `//= link grape_swagger_rails_manifest.{css,js}` to their own `app/assets/config/manifest.js`.
> Automatically register assets with Sprockets
